version: '3.9'

services:
  my-elast:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elast_data:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
    ulimits:
      nofile:
        soft: 98304
        hard: 98304

volumes:
  elast_data: